import { describe, it, expect } from 'vitest';
import fc from 'fast-check';
import { hashPassword, comparePassword, generateToken, validateToken, validateEmail, register, login } from '../../src/services/auth';
import bcrypt from 'bcrypt';
import jwt from 'jsonwebtoken';
import { config } from '../../src/config/env';
import { PrismaClient } from '@prisma/client';

/**
 * **Validates: Requirements 1.3**
 * 
 * Property 3: Password Hashing Security
 * For any password provided during registration, the stored hash should be generated 
 * using bcrypt with salt rounds >= 10, and the original password should never be 
 * stored in plain text.
 */
describe('Feature: seo-saas-platform, Authentication Properties', () => {
  describe('Property 3: Password Hashing Security', () => {
    it('should hash passwords with bcrypt using salt rounds >= 10', async () => {
      await fc.assert(
        fc.asyncProperty(
          fc.string({ minLength: 8, maxLength: 50 }),
          async (password) => {
            const hash = await hashPassword(password);
            
            // Verify hash is not the plain password
            expect(hash).not.toBe(password);
            
            // Verify hash starts with bcrypt identifier
            expect(hash).toMatch(/^\$2[aby]\$/);
            
            // Extract salt rounds from hash (format: $2a$10$...)
            const saltRounds = parseInt(hash.split('$')[2]);
            expect(saltRounds).toBeGreaterThanOrEqual(10);
            
            // Verify the hash can be used to validate the original password
            const isValid = await bcrypt.compare(password, hash);
            expect(isValid).toBe(true);
          }
        ),
        { numRuns: 20 }
      );
    });

    it('should correctly compare passwords with hashes', async () => {
      await fc.assert(
        fc.asyncProperty(
          fc.string({ minLength: 8, maxLength: 50 }),
          fc.string({ minLength: 8, maxLength: 50 }),
          async (password, wrongPassword) => {
            fc.pre(password !== wrongPassword); // Ensure passwords are different
            
            const hash = await hashPassword(password);
            
            // Correct password should match
            const correctMatch = await comparePassword(password, hash);
            expect(correctMatch).toBe(true);
            
            // Wrong password should not match
            const wrongMatch = await comparePassword(wrongPassword, hash);
            expect(wrongMatch).toBe(false);
          }
        ),
        { numRuns: 20 }
      );
    });
  });

  /**
   * **Validates: Requirements 1.6, 2.4**
   * 
   * Property 6: JWT Token Expiration
   * For any JWT token generated by the Auth_Service (during registration or login), 
   * the token's expiration time should be exactly 24 hours from the creation time.
   */
  describe('Property 6: JWT Token Expiration', () => {
    it('should generate tokens with exactly 24h expiration', () => {
      fc.assert(
        fc.property(
          fc.uuid(),
          fc.constantFrom('Free' as const, 'Pro' as const, 'Admin' as const),
          (userId, role: 'Free' | 'Pro' | 'Admin') => {
            const beforeGeneration = Math.floor(Date.now() / 1000);
            const token = generateToken(userId, role);
            const afterGeneration = Math.floor(Date.now() / 1000);
            
            const decoded = jwt.decode(token) as any;
            
            // Verify expiration is 24 hours (86400 seconds) from creation
            const expectedExpMin = beforeGeneration + 86400;
            const expectedExpMax = afterGeneration + 86400;
            
            expect(decoded.exp).toBeGreaterThanOrEqual(expectedExpMin);
            expect(decoded.exp).toBeLessThanOrEqual(expectedExpMax);
            
            // Verify iat (issued at) is set
            expect(decoded.iat).toBeGreaterThanOrEqual(beforeGeneration);
            expect(decoded.iat).toBeLessThanOrEqual(afterGeneration);
          }
        ),
        { numRuns: 50 }
      );
    });
  });

  /**
   * **Validates: Requirements 2.3, 2.5**
   * 
   * Property 8: JWT Token Structure
   * For any valid authentication (registration or login), the generated JWT token 
   * should contain userId and role in the payload and use HS256 algorithm for signing.
   */
  describe('Property 8: JWT Token Structure', () => {
    it('should include userId and role in token payload with HS256 algorithm', () => {
      fc.assert(
        fc.property(
          fc.uuid(),
          fc.constantFrom('Free' as const, 'Pro' as const, 'Admin' as const),
          (userId, role: 'Free' | 'Pro' | 'Admin') => {
            const token = generateToken(userId, role);
            
            // Decode without verification to check structure
            const decoded = jwt.decode(token, { complete: true }) as any;
            
            // Verify algorithm is HS256
            expect(decoded.header.alg).toBe('HS256');
            
            // Verify payload contains userId and role
            expect(decoded.payload.userId).toBe(userId);
            expect(decoded.payload.role).toBe(role);
            
            // Verify token can be validated
            const validated = validateToken(token);
            expect(validated.userId).toBe(userId);
            expect(validated.role).toBe(role);
          }
        ),
        { numRuns: 50 }
      );
    });
  });

  /**
   * **Validates: Requirements 3.1**
   * 
   * Property 10: JWT Signature Validation
   * For any JWT token, the API_Gateway should accept tokens with valid signatures 
   * and reject tokens with invalid or missing signatures.
   */
  describe('Property 10: JWT Signature Validation', () => {
    it('should accept valid tokens and reject invalid tokens', () => {
      fc.assert(
        fc.property(
          fc.uuid(),
          fc.constantFrom('Free' as const, 'Pro' as const, 'Admin' as const),
          (userId, role: 'Free' | 'Pro' | 'Admin') => {
            // Generate valid token
            const validToken = generateToken(userId, role);
            
            // Should validate successfully
            const decoded = validateToken(validToken);
            expect(decoded.userId).toBe(userId);
            expect(decoded.role).toBe(role);
            
            // Tamper with token (change last character)
            const tamperedToken = validToken.slice(0, -1) + 'X';
            
            // Should reject tampered token
            expect(() => validateToken(tamperedToken)).toThrow();
          }
        ),
        { numRuns: 50 }
      );
    });

    it('should reject tokens signed with wrong secret', () => {
      fc.assert(
        fc.property(
          fc.uuid(),
          fc.constantFrom('Free' as const, 'Pro' as const, 'Admin' as const),
          (userId, role: 'Free' | 'Pro' | 'Admin') => {
            // Generate token with wrong secret
            const wrongToken = jwt.sign(
              { userId, role },
              'wrong-secret',
              { algorithm: 'HS256', expiresIn: '24h' }
            );
            
            // Should reject token with wrong signature
            expect(() => validateToken(wrongToken)).toThrow('Invalid token');
          }
        ),
        { numRuns: 50 }
      );
    });
  });

  /**
   * **Validates: Requirements 3.3**
   * 
   * Property 11: Role Extraction from Token
   * For any valid JWT token, the API_Gateway should correctly extract the user role 
   * from the token payload.
   */
  describe('Property 11: Role Extraction from Token', () => {
    it('should correctly extract role from valid tokens', () => {
      fc.assert(
        fc.property(
          fc.uuid(),
          fc.constantFrom('Free' as const, 'Pro' as const, 'Admin' as const),
          (userId, role: 'Free' | 'Pro' | 'Admin') => {
            const token = generateToken(userId, role);
            const decoded = validateToken(token);
            
            // Verify role is correctly extracted
            expect(decoded.role).toBe(role);
            expect(['Free', 'Pro', 'Admin']).toContain(decoded.role);
          }
        ),
        { numRuns: 50 }
      );
    });
  });

  /**
   * **Validates: Requirements 1.1**
   * 
   * Property 1: Email Format Validation
   * For any string input to the registration endpoint, the Auth_Service should 
   * correctly identify whether it matches valid email format (RFC 5322) and 
   * reject invalid formats.
   */
  describe('Property 1: Email Format Validation', () => {
    it('should accept valid email formats', () => {
      fc.assert(
        fc.property(
          fc.emailAddress(),
          (email) => {
            const isValid = validateEmail(email);
            expect(isValid).toBe(true);
          }
        ),
        { numRuns: 50 }
      );
    });

    it('should reject invalid email formats', () => {
      fc.assert(
        fc.property(
          fc.oneof(
            fc.string().filter(s => !s.includes('@')),
            fc.string().map(s => s + '@'),
            fc.string().map(s => '@' + s),
            fc.string().map(s => s.replace(/\./g, ''))
          ),
          (invalidEmail) => {
            const isValid = validateEmail(invalidEmail);
            expect(isValid).toBe(false);
          }
        ),
        { numRuns: 50 }
      );
    });
  });

  /**
   * **Validates: Requirements 1.2**
   * 
   * Property 2: Duplicate Email Detection
   * For any email that has already been registered, attempting to register 
   * the same email again should return an error indicating the email is 
   * already registered.
   */
  describe('Property 2: Duplicate Email Detection', () => {
    it('should reject duplicate email registrations', async () => {
      const prisma = new PrismaClient();

      await fc.assert(
        fc.asyncProperty(
          fc.emailAddress(),
          fc.string({ minLength: 8, maxLength: 50 }),
          async (email, password) => {
            try {
              // First registration should succeed
              const result1 = await register(email, password);
              expect(result1.token).toBeDefined();
              expect(result1.user.email).toBe(email);

              // Second registration with same email should fail
              await expect(register(email, password)).rejects.toThrow('Email already registered');

              // Cleanup
              await prisma.user.delete({ where: { email } });
            } catch (error: any) {
              // If first registration fails due to existing email, cleanup and skip
              if (error.message === 'Email already registered') {
                await prisma.user.delete({ where: { email } }).catch(() => {});
                fc.pre(false);
              }
              throw error;
            }
          }
        ),
        { numRuns: 10 }
      );

      await prisma.$disconnect();
    });
  });

  /**
   * **Validates: Requirements 1.4**
   * 
   * Property 4: Default Role Assignment
   * For any new user registration, the created user should have the role 
   * set to "Free" by default.
   */
  describe('Property 4: Default Role Assignment', () => {
    it('should assign Free role to all new users', async () => {
      const prisma = new PrismaClient();

      await fc.assert(
        fc.asyncProperty(
          fc.emailAddress(),
          fc.string({ minLength: 8, maxLength: 50 }),
          async (email, password) => {
            try {
              const result = await register(email, password);
              
              // Verify role is Free
              expect(result.user.role).toBe('Free');

              // Cleanup
              await prisma.user.delete({ where: { email } });
            } catch (error: any) {
              // If registration fails due to existing email, cleanup and skip
              if (error.message === 'Email already registered') {
                await prisma.user.delete({ where: { email } }).catch(() => {});
                fc.pre(false);
              }
              throw error;
            }
          }
        ),
        { numRuns: 10 }
      );

      await prisma.$disconnect();
    });
  });

  /**
   * **Validates: Requirements 1.5**
   * 
   * Property 5: Registration Round-Trip
   * For any valid registration data (email and password), after successful 
   * registration, querying the database for that email should return a user 
   * record with matching email and verifiable password hash.
   */
  describe('Property 5: Registration Round-Trip', () => {
    it('should store and retrieve user data correctly', async () => {
      const prisma = new PrismaClient();

      await fc.assert(
        fc.asyncProperty(
          fc.emailAddress(),
          fc.string({ minLength: 8, maxLength: 50 }),
          async (email, password) => {
            try {
              // Register user
              const result = await register(email, password);
              expect(result.user.email).toBe(email);

              // Query database
              const storedUser = await prisma.user.findUnique({
                where: { email },
              });

              // Verify data
              expect(storedUser).toBeDefined();
              expect(storedUser!.email).toBe(email);
              expect(storedUser!.role).toBe('Free');
              
              // Verify password hash (not plain text)
              expect(storedUser!.password).not.toBe(password);
              const isPasswordValid = await bcrypt.compare(password, storedUser!.password);
              expect(isPasswordValid).toBe(true);

              // Cleanup
              await prisma.user.delete({ where: { email } });
            } catch (error: any) {
              // If registration fails due to existing email, cleanup and skip
              if (error.message === 'Email already registered') {
                await prisma.user.delete({ where: { email } }).catch(() => {});
                fc.pre(false);
              }
              throw error;
            }
          }
        ),
        { numRuns: 10 }
      );

      await prisma.$disconnect();
    });
  });

  /**
   * **Validates: Requirements 2.1, 2.6**
   * 
   * Property 7: Login Credential Validation
   * For any login attempt, the Auth_Service should return success if and only if 
   * both the email exists in the database and the provided password matches the 
   * stored hash.
   */
  describe('Property 7: Login Credential Validation', () => {
    it('should authenticate valid credentials and reject invalid ones', async () => {
      const prisma = new PrismaClient();

      await fc.assert(
        fc.asyncProperty(
          fc.emailAddress(),
          fc.string({ minLength: 8, maxLength: 50 }),
          fc.string({ minLength: 8, maxLength: 50 }),
          async (email, correctPassword, wrongPassword) => {
            fc.pre(correctPassword !== wrongPassword); // Ensure passwords are different

            try {
              // Register user first
              await register(email, correctPassword);

              // Login with correct credentials should succeed
              const loginResult = await login(email, correctPassword);
              expect(loginResult.token).toBeDefined();
              expect(loginResult.user.email).toBe(email);

              // Login with wrong password should fail
              await expect(login(email, wrongPassword)).rejects.toThrow('Invalid credentials');

              // Login with non-existent email should fail
              await expect(login('nonexistent@example.com', correctPassword)).rejects.toThrow('Invalid credentials');

              // Cleanup
              await prisma.user.delete({ where: { email } });
            } catch (error: any) {
              // If registration fails due to existing email, cleanup and skip
              if (error.message === 'Email already registered') {
                await prisma.user.delete({ where: { email } }).catch(() => {});
                fc.pre(false);
              }
              throw error;
            }
          }
        ),
        { numRuns: 10 }
      );

      await prisma.$disconnect();
    });
  });

  /**
   * **Validates: Requirements 2.6**
   * 
   * Property 9: Authentication Response Completeness
   * For any successful authentication, the response should include both a valid 
   * JWT token and complete user profile data (id, email, role).
   */
  describe('Property 9: Authentication Response Completeness', () => {
    it('should return complete authentication response', async () => {
      const prisma = new PrismaClient();

      await fc.assert(
        fc.asyncProperty(
          fc.emailAddress(),
          fc.string({ minLength: 8, maxLength: 50 }),
          async (email, password) => {
            try {
              // Register user
              const registerResult = await register(email, password);
              
              // Verify registration response completeness
              expect(registerResult.token).toBeDefined();
              expect(registerResult.user).toBeDefined();
              expect(registerResult.user.id).toBeDefined();
              expect(registerResult.user.email).toBe(email);
              expect(registerResult.user.role).toBe('Free');
              expect(registerResult.user.createdAt).toBeDefined();

              // Verify token is valid
              const decodedRegister = validateToken(registerResult.token);
              expect(decodedRegister.userId).toBe(registerResult.user.id);
              expect(decodedRegister.role).toBe(registerResult.user.role);

              // Login with same credentials
              const loginResult = await login(email, password);
              
              // Verify login response completeness
              expect(loginResult.token).toBeDefined();
              expect(loginResult.user).toBeDefined();
              expect(loginResult.user.id).toBe(registerResult.user.id);
              expect(loginResult.user.email).toBe(email);
              expect(loginResult.user.role).toBe('Free');
              expect(loginResult.user.createdAt).toBeDefined();

              // Verify token is valid
              const decodedLogin = validateToken(loginResult.token);
              expect(decodedLogin.userId).toBe(loginResult.user.id);
              expect(decodedLogin.role).toBe(loginResult.user.role);

              // Cleanup
              await prisma.user.delete({ where: { email } });
            } catch (error: any) {
              // If registration fails due to existing email, cleanup and skip
              if (error.message === 'Email already registered') {
                await prisma.user.delete({ where: { email } }).catch(() => {});
                fc.pre(false);
              }
              throw error;
            }
          }
        ),
        { numRuns: 10 }
      );

      await prisma.$disconnect();
    });
  });
});
